services:
  database:
    container_name: postgres-dev
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network

  # DESCOMENTAR CASO PRECISE DE EDITOR SQL (PG Admin)
  #
  #teste-pgadmin-compose:
  #  image: dpage/pgadmin4
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: "example@example.com"
  #    PGADMIN_DEFAULT_PASSWORD: "changeme"
  #  ports:
  #    - "16543:80"
  #  depends_on:
  #    - database
  #  networks:
  #    - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
